WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe454fdd420>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b814dcca-32d0-4a83-afc4-7e5153e56cb0
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe454fde470>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b814dcca-32d0-4a83-afc4-7e5153e56cb0
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe454fdd780>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b814dcca-32d0-4a83-afc4-7e5153e56cb0