WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f295259b3d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6b0091f-6777-4cad-98c5-40027373c163
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f295259aec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6b0091f-6777-4cad-98c5-40027373c163
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f295259afe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a6b0091f-6777-4cad-98c5-40027373c163