WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fade68bb4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f9c3be6c-8ff1-45f0-ab6f-f484222e99fd
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fade68bb220>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f9c3be6c-8ff1-45f0-ab6f-f484222e99fd
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fade68bb700>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f9c3be6c-8ff1-45f0-ab6f-f484222e99fd