WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6978053730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b90e9146-a28c-4f21-98cc-d5cb22810853
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69780530a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b90e9146-a28c-4f21-98cc-d5cb22810853
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f697817a5f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b90e9146-a28c-4f21-98cc-d5cb22810853