WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e06f675b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6c72e9fc-5acd-4d59-a663-79ccf68ed068
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e06f67760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6c72e9fc-5acd-4d59-a663-79ccf68ed068
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e06f67160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6c72e9fc-5acd-4d59-a663-79ccf68ed068