WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1584c8f370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/57a8e102-b681-4045-a43b-69c5525cb058
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1584c8f0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/57a8e102-b681-4045-a43b-69c5525cb058
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1584c8f5e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/57a8e102-b681-4045-a43b-69c5525cb058