WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efeb84ff520>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab83417f-b06a-4616-83ad-cc3df603ae29
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efeb84ff340>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab83417f-b06a-4616-83ad-cc3df603ae29
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efeb84ff730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ab83417f-b06a-4616-83ad-cc3df603ae29