WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8dc1d5f60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/07443748-1a7d-48af-b008-33c09165f941
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8dc1d5de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/07443748-1a7d-48af-b008-33c09165f941
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe8dc1d5a80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/07443748-1a7d-48af-b008-33c09165f941