WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69fe3af310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/de3e863f-4ea6-4f80-8e44-c883f3481eea
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69fe3af1f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/de3e863f-4ea6-4f80-8e44-c883f3481eea
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69fe3af4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/de3e863f-4ea6-4f80-8e44-c883f3481eea